# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.box = "bento-centos65"
  config.vm.box_check_update = false

  config.vm.define :chef  do |node|
    node.vm.network :forwarded_port, guest: 22, host: 2001, id: "ssh"
    node.vm.network :private_network, ip: "192.168.33.11"
  end

  config.vm.define :node  do |node|
    node.vm.network :forwarded_port, guest: 22, host: 2002, id: "ssh"
    node.vm.network :private_network, ip: "192.168.33.12"
  end

end
